app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField

class PokemonForm(FlaskForm):
    submit = SubmitField('New Pokemon')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from .config import config
from dotenv import load_dotenv

load_dotenv(".env")

bootstrap = Bootstrap()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms

app/main/views.py
from flask import render_template
from . import main
import pymongo as pm
import os

client = pm.MongoClient(os.environ.get('MONGO_URI'))
db = client[os.environ.get('ENVIRONMENT')]['post']

#Home page
@main.route('/')
def index():
    #Get latest post
    post = db.find().sort("modified_date", pm.DESCENDING).limit(1)
    return render_template('main/index.html', post=post[0])

#Book blog
@main.route('/blog')
def blog():
    #Get all posts, newest first
    posts = db.find().sort("modified_date", pm.DESCENDING)
    return render_template('main/blog.html', posts=posts)

app/templates/_macros.html
<!--Macros for use in templates-->
{% macro render_blog_post(post, id) %}
    <div class="container shadow post" style="padding: 0px;">
        <div class="container post-title-block pt-3">
            <div class="row">
                <div class="col">
                    <h4 class="post-title ml-auto">{{ post['title'] }}</h4>
                        <div class="col post-tags">
                            {% for tag in post['tags'] %}
                                <span class="badge tag badge-light pr-2 pl-2 pt-1 pb-1">{{ tag }}</span>
                            {% endfor %}
                        </div> 
                </div>
                <div class="col">
                    <a class="btn btn-sm expand-button float-right" data-toggle="collapse" href="#post{{ id }}" role="button">
                        <img src="{{ url_for('static', filename='icons/plus.png', _external=True) }}">
                    </a>
                </div>
            </div>
        </div>
        <div class="container collapse post-content-block" id="post{{ id }}">
            <p class="post-content">{{ post['content'] }}</p>
        </div>
    </div>
{% endmacro %}

{% macro render_project(title, description, tags, link) %}
    <div class="card-project shadow pt-3 pr-3">
        <div class="card-body" style="position: relative;">
            <div class="container d-flex align-items-center" style="padding-left: 0px;">
                <img src="{{ url_for('static', filename='icons/repo.png', _external=True) }}" class="repo-icon">
                <a href="{{ link }}" target="_blank">
                    <h3 class="repo-title">{{ title }}</h3>
                </a>
            </div>
            <p class="repo-description">{{ description }}</p>
        </div>
        <div class="card-footer d-flex align-items-start flex-wrap" style="padding-bottom: 0px;">
            {% for tag in tags %}
                <p class="repo-tag pr-3">{{ tag }}</p>
            {% endfor %}
        </div>
    </div>
{% endmacro %}

app/templates/main/base.html
<head>
    <!-- Bootstrap required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="static/styles.css">
    <link rel="icon" type="image/png" href="static/images/logo.png">
    {% block head %}
    <title>Gerardo Salazar{% block title %}{% endblock %}</title>
    {% endblock %}
</head>

{% block body %}
    <body style="background-color:#212121">
        <!--Navbar-->
        {% block navbar %}
        <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#121212">
            <a class="navbar-brand" href="/">
                <img src="static/images/logo-2.png" style="max-width: 40%; height: auto;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <!--Navbar items-->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" style="font-size: 20px;" href="{{ url_for('main.blog', _external=True) }}">Blog</a>
                    </li>
                    <!--Restore if job searching-->
                    <!--
                    <li class="nav-item">
                        <a class="nav-link" target="_blank" href="{{ url_for('static', filename="resume.pdf", _external=True) }}">Resume</a>
                    </li>
                    -->
                </ul>
            </div>
        </nav>
        {% endblock %}
        
        <!--Bootstrap JavaScript-->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
{% endblock %}

<!--Everything above this line is common to every template, below this line is where template-unique content is included-->
{% block content %}
        {% block page_content %}
        {% endblock %}
{% endblock %}
</html>

app/templates/main/blog.html
{% extends "main/base.html" %}
{% import "_macros.html" as macros %}
{% block title %}'s Blog{% endblock %}
{% block content %} 
{% block page_content %}
<!--Blog Posts-->
{% for post in posts %}
    <div class="container pt-5" style="padding: 0px;">
        {{ macros.render_blog_post(post, loop.index) }}
    </div>
{% endfor %}
{% endblock %} 
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %} 
{% import "_macros.html" as macros %}
{% block content %} 
{% block page_content %}
<!--Title Block-->
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-flex sol-sm-auto col-md-auto col-lg-auto">
        <h4 class="mt-0">Hi, I'm</h4>
        <h1 class="mt-1">Gerardo Salazar</h1>
      </div>
      <div class="col col-sm-auto col-lg-7">
        <p class="mt-2">I'm an avid learner with a passion for making the world a better place through science and technology</p>
      </div>
    </div>
    <div>
      <div class="container-fluid d-flex justify-content-lg-start 
      justify-content-md-start justify-content-sm-center mt-5 justify-content-xs-center flex-wrap" style="padding: 0px;">
        <a class="btn btn-primary btn-lg mr-5" id="email-button" href="mailto:gerardo.salazar@utexas.edu" target="_blank" type="button">
          Email Me
        </a>
      </div>
      <div class="container-fluid d-flex justify-content-lg-start 
      justify-content-sm-center justify-content-md-start justify-content-xs-center mt-5" style="padding: 0px;">
        <a href="https://github.com/Salazar-99" target="_blank" class="pr-2">
          <img class="github" src="{{ url_for('static', filename='icons/github-fill.png', _external=True) }}">  
        </a>
        <a href="https://www.linkedin.com/in/gerardo-salazar-62196a148/" target="_blank">
          <img class="linkedin" src="{{ url_for('static', filename='icons/linkedin-box-fill.png', _external=True) }}">  
        </a>
      </div>
    </div>
  </div>
</div>
<!--About Me-->
<div class="jumbotron" style="padding-top: 0px;">
  <div class="container">
    <div class="row justify-content-center pb-4">
      <h2 class="mt-0">About Me</h2>
    </div>
    <div class="container d-flex flex-column flex-lg-row align-items-start" style="padding: 0px;">
      <div class="container pt-3" style="padding: 0px;">
        <p class="about">
          I double majored in Physics and Math at The University of Texas at Austin.
          I love learning about all things science but especially
          physics, math, and computing.
        </p>
        <p class="about">
          I am currently working as a Data Scientist in Houston.
          In my spare time I enjoy playing golf, video games, reading, and exercising.
        </p>
        <p class="about">
          I am fascinated by software and enjoy learning about all of its subdisciplines. I've worked on full-stack web development, machine learning and data science, CLI tools, and more recently
          have taken an interest in cloud infrastructure and DevOps.
        </p>
      </div>
      <div class="container d-flex justify-content-center pt-3">
        <img class="me shadow" src="{{ url_for('static', filename='images/me.jpg', _external=True) }}">
      </div>
    </div>
  </div>
</div>
<!--Last Blog Post-->
<div class="jumbotron" style="padding-top: 0px;">
  <div class="container">
    <div class="row justify-content-center pb-4">
      <h2 class="mt-0">My Blog</h2>
    </div>
    <div class="container d-flex flex-column flex-lg-row align-items-start pb-4" style="padding: 0px;">
      <div class="container" style="padding: 0px;">
        <p class="about">
          I find that writing about the things I'm working on or reading helps me internalize what I've learned.
          My blog is a collection of such writings and will probably include some random musings as well. 
          I hope that my posts can offer some insight into the topics they cover or serve as reading recommendations for people curious about the same things as I am.
          I'm happy to discuss any of my writings so if you want to discuss any of them feel free to send me an email. My latest post is below.
        </p>
      </div>
    </div>
    <div class="container" style="padding: 0px;">
      {{ macros.render_blog_post(post, id=1) }}
    </div>
  </div>
</div>
<!--Projects-->
<div class="jumbotron" style="padding-top: 0px;">
  <div class="container">
    <div class="row justify-content-center pb-5">
      <h2 class="mt-0">Some Projects</h2>
    </div>
    <div class="container d-flex flex-column flex-lg-row align-items-start">
      <div class="row">
        <div class="col-sm-6 pt-3">
          <div class="card-deck">
            {{ macros.render_project(title="This Pokemon Does Not Exist", description="Modular implementation of CVAE and GAN deep generative models for producing images of \"new\" Pokemon.", tags=["Python", "Tensorflow"], link="https://github.com/Salazar-99/This-Pokemon-Does-Not-Exist") }}
            {{ macros.render_project(title="Gravitational WaveNet", description="Implementation of a deep learning architecture for gravitational wave classification with experiment framework", tags=["Python", "Tensorflow", "Physics"], link="https://github.com/Salazar-99/Gravitational-WaveNet") }}
          </div>
        </div>
        <div class="col-sm-6 pt-3">
          <div class="card-deck">
            {{ macros.render_project(title="Athena", description="Resources for my Kubernetes homelab, helm charts, and manifests for applications deployed on it", tags=["Kubernetes", "GitOps", "CI/CD"], link="https://github.com/Salazar-99/Athena") }}
            {{ macros.render_project(title="Bookly", description="A small Python based REPL program for managing my MongoDB-based blog. Written using the click and click-repl libraries.", tags=["Python", "Click", "MongoDB"], link="https://github.com/Salazar-99/Bookly") }}
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
<!--Footer-->
<footer class="page-footer font-small pt-4" style="background-color: black;">
  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">
      <div class="row">
          <div class="col-md-6 mt-md-0 mt-3">
              <p><font color="white">See the <a href="https://github.com/Salazar-99/Personal-Website" target="_blank">source code</a> for this site.</font>
          </div>
      </div>
  </div>
</footer>
{% endblock %} 
{% endblock %}